/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package adithfrozen;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo - GK
 */
public class editData extends javax.swing.JFrame {

    /**
     * Creates new form addData
     */
    private Connection con;
    private Statement stat;
    private ResultSet res;

    private int ID = lihatData.IDB;

    public editData() {
        initComponents();
        Date date = new Date();
        datechoose.setMinSelectableDate(date);
        loadInput();
    }

    private void cls() {
        txtharga.setText("");
        txtmerk.setText("");
        txtnama.setText("");
        Date date = new Date();
        datechoose.setDate(date);
        rbkentang.setSelected(false);
        rbnugget.setSelected(false);
        rbselada.setSelected(false);
        rbsosis.setSelected(false);
    }

    private void loadInput() {
        try {
            con = koneksi.getConnection();
            String sql = "SELECT * FROM barang WHERE id_barang = " + ID;
            stat = con.createStatement();
            res = stat.executeQuery(sql);

            if (res.next()) {
                ID = res.getInt("id_barang");
                this.txtnama.setText(res.getString("nama"));
                this.txtmerk.setText(res.getString("merk"));
                this.datechoose.setDate(res.getDate("tanggal_kadaluarsa"));
                if (res.getString("jenis").equals(rbkentang.getText())) {
                    rbkentang.setSelected(true);
                } else if (res.getString("jenis").equals(rbnugget.getText())) {
                    rbnugget.setSelected(true);
                } else if (res.getString("jenis").equals(rbselada.getText())) {
                    rbselada.setSelected(true);
                } else if (res.getString("jenis").equals(rbsosis.getText())) {
                    rbsosis.setSelected(true);
                }
                this.txtharga.setText(String.valueOf(res.getInt("harga")));
            }
            res.close();
            stat.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "SQL Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtmerk = new javax.swing.JTextField();
        txtnama = new javax.swing.JTextField();
        rbnugget = new javax.swing.JRadioButton();
        rbsosis = new javax.swing.JRadioButton();
        rbselada = new javax.swing.JRadioButton();
        rbkentang = new javax.swing.JRadioButton();
        txtharga = new javax.swing.JTextField();
        btnubah = new javax.swing.JButton();
        btnback = new javax.swing.JButton();
        datechoose = new com.toedter.calendar.JCalendar();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Merk");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(72, 79, 37, 16);

        jLabel2.setText("Nama");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(72, 119, 37, 16);

        jLabel3.setText("Jenis");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(72, 158, 37, 16);

        jLabel4.setText("Harga");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(72, 234, 37, 16);

        jLabel5.setText("Tanggal Kadaluarsa");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(72, 271, 105, 16);
        getContentPane().add(txtmerk);
        txtmerk.setBounds(228, 76, 351, 22);
        getContentPane().add(txtnama);
        txtnama.setBounds(228, 116, 351, 22);

        buttonGroup1.add(rbnugget);
        rbnugget.setText("Nugget");
        getContentPane().add(rbnugget);
        rbnugget.setBounds(228, 156, 63, 21);

        buttonGroup1.add(rbsosis);
        rbsosis.setText("Sosis");
        getContentPane().add(rbsosis);
        rbsosis.setBounds(313, 156, 49, 21);

        buttonGroup1.add(rbselada);
        rbselada.setText("Selada");
        getContentPane().add(rbselada);
        rbselada.setBounds(313, 189, 59, 21);

        buttonGroup1.add(rbkentang);
        rbkentang.setText("Kentang");
        getContentPane().add(rbkentang);
        rbkentang.setBounds(228, 189, 67, 21);
        getContentPane().add(txtharga);
        txtharga.setBounds(228, 231, 351, 22);

        btnubah.setText("Ubah");
        btnubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnubahActionPerformed(evt);
            }
        });
        getContentPane().add(btnubah);
        btnubah.setBounds(406, 390, 72, 23);

        btnback.setText("Back");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });
        getContentPane().add(btnback);
        btnback.setBounds(507, 390, 72, 23);
        getContentPane().add(datechoose);
        datechoose.setBounds(228, 271, 351, 113);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 70, 580, 390);

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel6.setText("Menu Ubah Data");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(198, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(194, 194, 194))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 580, 70);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        // TODO add your handling code here:
        MenuAdmin MA = new MenuAdmin();
        MA.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnbackActionPerformed

    private void btnubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnubahActionPerformed
        // TODO add your handling code here:
        String merk, nama, jenis = null, tgl;
        int harga;
        merk = txtmerk.getText();
        nama = txtnama.getText();
        if (rbkentang.isSelected()) {
            jenis = rbkentang.getText();
        } else if (rbnugget.isSelected()) {
            jenis = rbnugget.getText();
        } else if (rbselada.isSelected()) {
            jenis = rbselada.getText();
        } else if (rbsosis.isSelected()) {
            jenis = rbsosis.getText();
        }
        harga = Integer.parseInt(txtharga.getText());
        java.util.Date date = datechoose.getDate();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        tgl = sdf.format(date);

        if (!merk.isEmpty() && !nama.isEmpty() && !jenis.isEmpty() && !tgl.isEmpty() && harga != 0) {

            try {
                Connection conn = koneksi.getConnection();
                String sql = "UPDATE barang SET merk = ?, nama = ?, jenis = ?, harga = ?, tanggal_kadaluarsa = ? WHERE id_barang = ?";
                PreparedStatement stmt = conn.prepareStatement(sql);
                stmt.setString(1, merk);
                stmt.setString(2, nama);
                stmt.setString(3, jenis);
                stmt.setInt(4, harga);
                stmt.setString(5, tgl);
                stmt.setInt(6, ID);

                int rowAffected = stmt.executeUpdate();
                if (rowAffected > 0) {
                    cls();
                    JOptionPane.showMessageDialog(this, "Berhasil Mengubah Barang!", "SQL Information", JOptionPane.INFORMATION_MESSAGE);
                    lihatData LD = new lihatData();
                    stmt.close();
                    lihatData.IDB = 0;
                    LD.setVisible(true);
                    dispose();
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "SQL Error", JOptionPane.ERROR_MESSAGE);
            }

        } else {
            JOptionPane.showMessageDialog(this, "Harap Isi Seluruh Data!", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnubahActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnback;
    private javax.swing.JButton btnubah;
    private javax.swing.ButtonGroup buttonGroup1;
    private com.toedter.calendar.JCalendar datechoose;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton rbkentang;
    private javax.swing.JRadioButton rbnugget;
    private javax.swing.JRadioButton rbselada;
    private javax.swing.JRadioButton rbsosis;
    private javax.swing.JTextField txtharga;
    private javax.swing.JTextField txtmerk;
    private javax.swing.JTextField txtnama;
    // End of variables declaration//GEN-END:variables
}
